### ISSUE TITLE
oss_resumable.h missed in INSTALL part of CMakeLists.txt 

### ISSUE THREAD

**Issue by yuzhougit** [aliyun/aliyun-oss-c-sdk#28]
Hi, after i installed latest oss c sdk, i found oss_resumable.h is not installed into /usr/local/include, which could cause my program fail to compile.

Then I checked the CMakeLists.txt , i found oss_resumable.h missed in INSTALL part, please add it

**Comment by Jackson-soft** [comment]
same issue

**Comment by baiyubin** [comment]
Thanks for your feedback,  we has been fixed in version 2.4.1
