### ISSUE TITLE
oss_head_object()当object不存在时，没有一个明确的错误

### ISSUE THREAD

**Issue by kilowu** [aliyun/aliyun-oss-c-sdk#3]
调用oss_head_object()，当object不存在的时候，返回的status如下：

req_id: 56DCFA06DA14FDFF1BC21924
error_code: "UnkonwnError"
error_msg: ""

这里面有两个问题：
1. 这个error code反映不了到底这个请求是因为什么原因失败
2. error code有一处typo，应该是UnknownError

**Comment by qiyuewuyi** [comment]
1，head object的文件或者bucket不存在时，code为404，这时候，error_code和error_msg不清晰，这个是已知问题，需要对head object做特殊处理。后面版本会修复。
2，这个是有误，已经修复。
3，多谢

**Comment by kilowu** [comment]
请问下这个问题已经修复了吗

**Comment by baiyubin** [comment]
head object错误时server端只返回http code，没有error code和error message。
