### ISSUE TITLE
aos_should_retry 重试 BUG

### ISSUE THREAD

**Issue by wjzeng** [aliyun/aliyun-oss-c-sdk#32]
调用 OSS C API oss_get_object_to_buffer 出错

struct aos_status_s {
    int code; // > 0 http code
    char *error_code; // can't modify
    char *error_msg; // can't modify
    char *req_id;   // can't modify
};

aos_status_s 结构反馈的错误信息：

code -992 
error_code HttpIoError 
error_msg Timeout 
req_id 58EC0CD00731DD416E838728

aos_should_retry 函数的判断是否有BUG
应该判断 int code 的值，而不是判断 error_code

**Comment by baiyubin** [comment]
您好，3.5.1修复了这个问题。
