### ISSUE TITLE
请问aliyun-oss-c-sdk什么时候支持64位Windows库

### ISSUE THREAD

**Issue by jinlong0813** [aliyun/aliyun-oss-c-sdk#42]
请问aliyun-oss-c-sdk什么时候支持64位Windows库？

**Comment by jinlong0813** [comment]
怎么没有官方的回复一下呢~

**Comment by babosa** [comment]
我也来凑个热闹，确实做基于OSS的产品是需要64位SDK的^^

**Comment by hangzws** [comment]
目前已经提交x64版本的分支build_x64，大家可以下载试用，后续我们会将这个分支合并到主干。

**Comment by huiguangjun** [comment]
已经合到master分支
