### ISSUE TITLE
上传文件的md5怎么用

### ISSUE THREAD

**Issue by qq575654643** [aliyun/aliyun-oss-c-sdk#43]
文件上传是调用oss_append_object_from_file， 怎么把md5用起来？是放在Content-MD5还是调用后从resp_headers读md5跟本地文件的md5比较？有Demo吗？
aos_table_t *resp_headers使用后怎么释放？

**Comment by hangzws** [comment]
对的，append操作可以通过将md5值写入到Content-MD5的headers里，服务端会校验上传的数据是否正确。上传成功后，服务端会返回整个对象文件的64为crc值，这个跟上传单个文件不太一样。
aos_table_t *resp_headers不用用户自己释放，系统会自动释放。
