### ISSUE TITLE
上传本地文件到OSS，API提供问题

### ISSUE THREAD

**Issue by yeechongyeung** [aliyun/aliyun-oss-c-sdk#51]
void put_object_from_file() 实现上传本地文件到OSS介绍中描述：
通过oss_put_object_from_file接口，并指定fliepath参数，可以实现上传一个本地文件到OSS。

实际上，api提供的oss_put_object_from_file接口，并没有这个path参数，该如何解决。

[问题描述在：[官方问题描述链接](https://help.aliyun.com/document_detail/32136.html?spm=a2c4g.11186623.6.797.b6Pm5S)
问题代码在：aliyun-oss-c-sdk / oss_c_sdk_sample / oss_put_object_sample.c

**Comment by hangzws** [comment]
<
/*  
 * @brief  put oss object from file
 * @param[in]   options             the oss request options
 * @param[in]   bucket              the oss bucket name
 * @param[in]   object              the oss object name
 * @param[in]   filename            the filename to put
 * @param[in]   headers             the headers for request
 * @param[out]  resp_headers        oss server response headers
 * @return  aos_status_t, code is 2xx success, other failure
 */                                    
aos_status_t *oss_put_object_from_file(const oss_request_options_t *options,
                                       const aos_string_t *bucket,
                                       const aos_string_t *object,
                                       const aos_string_t *filename,
                                       aos_table_t *headers,
                                       aos_table_t **resp_headers);
>

这个的filename可以指定文件路径
