### ISSUE TITLE
CMake 参数错误

### ISSUE THREAD

**Issue by aggresss** [aliyun/aliyun-oss-c-sdk#68]
https://github.com/aliyun/aliyun-oss-c-sdk/blob/264839ac8dd355b2b586e2359c4324d3a991c39e/CMakeLists.txt#L24
应该改为：
set(CMAKE_CXX_FLAGS_COVERAGE " ${CMAKE_C_FLAGS_DEBUG} -fprofile-arcs -ftest-coverage")

**Comment by huiguangjun** [comment]
已经修改
