### ISSUE TITLE
程序逆初始化，没有需要的资源释放函数。

### ISSUE THREAD

**Issue by thtfpcuser** [aliyun/aliyun-oss-c-sdk#71]
目前已知oss_request_options_create 和 aos_http_controller_create没有相应的资源释放函数。

**Comment by huiguangjun** [comment]
这个是从apr pool 里分配出来的，destroy pool 后，相关的内存会释放掉。

**Comment by thtfpcuser** [comment]
依靠内存池帮助释放，如果没有内存池，只有malloc/free，这样的代码是不是泄漏呢？
