### ISSUE TITLE
编译失败 dereferencing pointer to incomplete type ‘mxml_node_t {aka struct _mxml_node_s}

### ISSUE THREAD

**Issue by zhaochengwei** [aliyun/aliyun-oss-c-sdk#77]
`~/oss_c_sdk/aliyun-oss-c-sdk-3.5.0$ make
Scanning dependencies of target oss_c_sdk_static
[  1%] Building C object CMakeFiles/oss_c_sdk_static.dir/oss_c_sdk/aos_status.o
oss_c_sdk/aliyun-oss-c-sdk-3.5.0/oss_c_sdk/aos_status.c: In function ‘aos_should_retry’:
oss_c_sdk/aliyun-oss-c-sdk-3.5.0/oss_c_sdk/aos_status.c:34:9: warning: unused variable ‘aos_error_code’ [-Wunused-variable]
     int aos_error_code = 0;
         ^~~~~~~~~~~~~~
oss_c_sdk/aliyun-oss-c-sdk-3.5.0/oss_c_sdk/aos_status.c: In function ‘aos_status_parse_from_body’:
**oss_c_sdk/aliyun-oss-c-sdk-3.5.0/oss_c_sdk/aos_status.c:95:26: error: dereferencing pointer to incomplete type ‘mxml_node_t {aka struct _mxml_node_s}’
  node_content = code_node->child->value.opaque;
                          ^~**
CMakeFiles/oss_c_sdk_static.dir/build.make:182: recipe for target 'CMakeFiles/oss_c_sdk_static.dir/oss_c_sdk/aos_status.o' failed
make[2]: *** [CMakeFiles/oss_c_sdk_static.dir/oss_c_sdk/aos_status.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/oss_c_sdk_static.dir/all' failed
make[1]: *** [CMakeFiles/oss_c_sdk_static.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2`

版本如下：
apr-1.7.0  
apr-util-1.6.1  
mxml-3.1

**Comment by huiguangjun** [comment]
你把 mxml 换成 2.x 的版本 后试试看。

**Comment by kangaxx** [comment]
3.1版本修改了mxml_node_t，去掉了child，还是用2.8版本吧，readme要不改下？

**Comment by huiguangjun** [comment]
https://github.com/aliyun/aliyun-oss-c-sdk/commit/b4253aa8f2d7fa6bf9aa6f94dc882469fb1d3367
