### ISSUE TITLE
centos编译时报错

### ISSUE THREAD

**Issue by longchun4835** [aliyun/aliyun-oss-c-sdk#94]
按照官网教程，在centos7环境下安装完依赖：
```
yum install cmake
yum install curl-devel apr-devel apr-util-devel  mxml mxml-devel
```
安装依赖如下：
![image](https://user-images.githubusercontent.com/33303744/90596858-79e46c80-e222-11ea-97c1-02e19273f5fc.png)
下载oss sdk 3.10.0后，cmake . 前未出现错误，make时报了如下错误：
![image](https://user-images.githubusercontent.com/33303744/90595843-4accfb80-e220-11ea-9ca2-777650692440.png)

**Comment by huiguangjun** [comment]
请使用 2.x 版本 的 mxml
